doctrine:
    dbal:
        types:
            app_tariff_price_net: App\Tariff\Doctrine\TariffPriceNetType
            app_tariff_id: App\Tariff\Doctrine\TariffIdType
    orm:
        mappings:
            Tariff:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Tariff/Model'
                prefix: 'App\Tariff\Model'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Tariff\Action\TariffHandler: ~
    App\Tariff\Model\Tariffs: ~
