doctrine:
    orm:
        mappings:
            TariffDetails:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/TariffDetails/Model'
                prefix: 'App\TariffDetails\Model'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
