parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '10.3'
        charset: utf8
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            app_money: App\Common\MoneyType

            app_datetime: App\Common\DateTimeType

            app_tariff_price_net: App\Tariff\Doctrine\TariffPriceNetType
            app_tariff_ids: App\Tariff\Doctrine\TariffIdsType
            app_tariff_id: App\Tariff\Doctrine\TariffIdType

            app_event_id: App\Event\Doctrine\EventIdType

            app_order_id: App\Order\Doctrine\OrderIdType
            app_order_ids: App\Order\Doctrine\OrderIdsType

            app_product_id: App\Product\Doctrine\ProductIdType

            app_promocode_id: App\Promocode\Doctrine\PromocodeIdType

            app_user_id: App\User\Doctrine\UserIdType
            app_user_fullname: App\User\Doctrine\UserFullNameType
            app_user_contacts: App\User\Doctrine\UserContactsType

            app_ticket_id: App\Product\Doctrine\TicketIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                JSON_GET_TEXT: \Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGetText
        mappings:
            Event:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Event/Model'
                prefix: 'App\Event\Model'
            Order:
                is_bundle: false
                prefix: 'App\Order\Model'
                type: annotation
                dir: '%kernel.project_dir%/src/Order/Model'
            Product:
                is_bundle: false
                prefix: 'App\Product\Model'
                type: annotation
                dir: '%kernel.project_dir%/src/Product/Model'
            ProductModel:
                is_bundle: false
                prefix: 'App\Product\Model'
                type: annotation
                dir: '%kernel.project_dir%/src/Product/Model'
            Promocode:
                is_bundle: false
                prefix: 'App\Promocode\Model'
                type: annotation
                dir: '%kernel.project_dir%/src/Promocode/Model'
            Tariff:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Tariff/Model'
                prefix: 'App\Tariff\Model'
            User:
                is_bundle: false
                prefix: 'App\User\Model'
                type: annotation
                dir: '%kernel.project_dir%/src/User/Model'
