#controllers:
#    resource: ../../src/Controller/
#    type: annotation
product:
    resource: ../../src/Product/Action
    type: annotation
tariff:
    resource: ../../src/Tariff/Action
    type: annotation
event.create_event:
    resource: ../../src/Event/Action
    type: annotation
order.place_order:
    resource: ../../src/Order/Action/PlaceOrder/
    type: annotation
user_controller:
    resource: ../../src/User/Action/
    type: annotation
queries:
    resource: ../../src/Queries/
    type: annotation
