#controllers:
#    resource: ../../src/Controller/
#    type: annotation
order.place_order:
    resource: ../../src/Order/Action/PlaceOrder/
    type: annotation
user_controller:
    resource: ../../src/User/Action/
    type: annotation
queries:
    resource: ../../src/Queries/
    type: annotation
