services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Infrastructure\Persistence\DatabaseSerializer\DatabaseSerializer:
        arguments:
            - !service
                class: Symfony\Component\Serializer\Serializer
                arguments:
                    $normalizers:
                        - !service
                            class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
                            arguments:
                                $defaultContext:
                                    !php/const Symfony\Component\Serializer\Normalizer\DateTimeNormalizer::FORMAT_KEY: !php/const DateTimeInterface::ATOM # todo microsecs ?
                                    !php/const Symfony\Component\Serializer\Normalizer\DateTimeNormalizer::TIMEZONE_KEY: 'UTC'
                        - '@serializer.denormalizer.array'
                        - !service
                            class: App\Infrastructure\MoneyNormalizer
                        - !service
                            class: App\Infrastructure\InlineNormalizer\InlineNormalizer
                            arguments:
                                - '@annotations.reader'
                                - '@serializer.mapping.class_metadata_factory'
                                - '@serializer.name_converter.camel_case_to_snake_case'
                                - '@property_info.php_doc_extractor'
                                - '@serializer.mapping.class_discriminator_resolver'
                        - !service
                            class: App\Infrastructure\WithoutConstructorPropertyNormalizer
                            arguments:
                                - '@serializer.mapping.class_metadata_factory'
                                - '@serializer.name_converter.camel_case_to_snake_case'
                                - '@property_info.php_doc_extractor'
                                - '@serializer.mapping.class_discriminator_resolver'
                    $encoders:
                        - '@serializer.encoder.json'
