services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Product\Action\SendTicket\SendTicketHandler: ~

    App\Product\Action\SendTicket\FindTicketEmail\FindTicketEmail: ~

    App\Product\Action\SendTicket\TicketSending\TicketSending:
        arguments:
            $mailer: !service
                class: Swift_Mailer
                arguments:
                    $transport: !service
                        class: App\Infrastructure\Email\HttpEmailTransport
                        arguments:
                            $client: !service
                                class: GuzzleHttp\Client
                                arguments:
                                    $config:
                                        base_uri: 'http://localhost:8001'
            $from: '%app.no_reply_email%'
