doctrine:
    dbal:
        types:
            app_order_id: App\Order\Doctrine\OrderIdType
    orm:
        mappings:
            Order:
                is_bundle: false
                prefix: 'App\Order\Model'
                type: annotation
                dir: '%kernel.project_dir%/src/Order/Model'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Order\Action\OrderHandler: ~
    App\Order\Model\Orders: ~
    App\Order\Model\OrderMarkedPaid: ~
    App\Order\OrderNotificationSubscriber:
        tags:
            - { name: app.notification_subscriber }
