doctrine:
    dbal:
        types:
            app_user_id: App\User\Doctrine\UserIdType
            app_user_fullname: App\User\Doctrine\UserFullNameType
            app_user_contacts: App\User\Doctrine\UserContactsType
    orm:
        mappings:
            User:
                is_bundle: false
                prefix: 'App\User\Model'
                type: annotation
                dir: '%kernel.project_dir%/src/User/Model'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\User\Action\UserHandler: ~
    App\User\Model\Users: ~
