services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Infrastructure\Http\RequestResolver\AppRequestValidator: ~

    # LISTENER FOR VALIDATION ERRORS HANDLING
    App\Infrastructure\Http\RequestResolver\InvalidAppRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # RESOLVER FOR INJECTING APP REQUESTS AS HTTP ADAPTERS METHODS ARGUMENTS
    App\Infrastructure\Http\RequestResolver\AppRequestResolver:
        arguments:
            $serializer: '@app.infrastructure.http.serializer'
