version: '3'
services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:1.12
    ports:
      - ${COMPOSE_WEB_PORT}
    networks:
      default:
        ipv4_address: ${COMPOSE_NETWORK_BASE_ADDRESS}2
    volumes:
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
      - ./../:/var/www/html
  backend:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    environment:
      PHP_IDE_CONFIG: serverName=local
      XDEBUG_CONFIG: ide
    build:
      context: ./php
      args:
        - HOST_UID=${HOST_UID}
    user: ${HOST_UID}
    networks:
      default:
        ipv4_address: ${COMPOSE_NETWORK_BASE_ADDRESS}3
    volumes:
      - ./../:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-pgsql
    image: postgres:10.3
    networks:
      default:
        ipv4_address: ${COMPOSE_NETWORK_BASE_ADDRESS}4
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${COMPOSE_NETWORK_BASE_ADDRESS}0/16
