doctrine:
    dbal:
        types:
            app_promocode_id: App\Promocode\Doctrine\PromocodeIdType
            app_promocode_discount: App\Promocode\Doctrine\PromocodeDiscountType
            app_promocode_allowed_tariffs: App\Promocode\Doctrine\PromocodeAllowedTariffsType
            app_promocode_used_in_orders: App\Promocode\Doctrine\PromocodeUsedInOrdersType
    orm:
        mappings:
            Promocode:
                is_bundle: false
                prefix: 'App\Promocode\Model'
                type: annotation
                dir: '%kernel.project_dir%/src/Promocode/Model'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Promocode\Action\PromocodeHandler: ~
    App\Promocode\Model\FixedPromocodes: ~
