doctrine:
    dbal:
        types:
            app_product_id: App\Product\Doctrine\ProductIdType
            app_product_type: App\Product\Doctrine\ProductTypeType
            app_ticket_id: App\Product\Doctrine\TicketIdType
    orm:
        mappings:
            Product:
                is_bundle: false
                prefix: 'App\Product\Model'
                type: annotation
                dir: '%kernel.project_dir%/src/Product/Model'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Product\Action\ProductHandler: ~
    App\Product\Model\Products: ~
    App\Product\Model\Tickets: ~

    App\Product\Service\ProductEmailDelivery:
        arguments:
            $mailer: !service
                class: Swift_Mailer
                arguments:
                    $transport: !service
                        class: App\Infrastructure\Email\HttpEmailTransport
                        arguments:
                            $client: !service
                                class: GuzzleHttp\Client
                                arguments:
                                    $config:
                                        base_uri: 'http://localhost:8001'
            $productEmailFactoryDispatcher: !service
                class: App\Product\Service\ProductEmailFactoryDispatcher
                arguments:
                    $factoryMap:
                        !php/const App\Product\Model\ProductType::TICKET: !service
                            class: App\Product\Service\TicketEmailFactory
                            arguments:
                                $findTicketEmail: !service
                                    class: App\Product\Service\FindTicketEmail
                                    arguments:
                                        $connection: '@doctrine.dbal.default_connection'
                                $from: '%app.no_reply_email%'
